### ISSUE TITLE
Miscellaneous TODO

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#88]
- [x] Warning when `pcut` < 2.  ACEsuit/ACE1.jl#58
- [x] In TiAl tutorial `pcut = 1`, should be 2. #89
- [x] In all tutorials exploit defaults more? 
- [x] allow `wL` to be an argument for `ace_basis` then remove it from tutorials,  ACEsuit/ACE1.jl#58 and #89
- [x] remove `SparsePSH` from the basic tutorials, it is confusing, #89

... more soon.
